12141617 정규호
# Initialization

First, we start from importing some fundamental libraries.
'numpy' is used for matrix operations, and scipy.special has been brought to use sigmoid function. Also, we set the value of n_of_epochs, which is the number of trial we would go through for training.

In [1]:
import numpy as np
import scipy.special

sigmoid_f = lambda x: scipy.special.expit(x)

n_of_epochs = 800

Below is the input matrix, input.

In [2]:
input = np.asarray([[0.9, 0.1, 0.8]]).T
print(input.shape)
print(input)

(3, 1)
[[0.9]
 [0.1]
 [0.8]]


We also need to set the target value, which is alrady given.

In [3]:
target = np.asarray([[0.6, 0.8, 0.5]]).T
print(input.shape)
print(target)

(3, 1)
[[0.6]
 [0.8]
 [0.5]]


Below are the given input-hidden weight and hidden-output weight matrices.

In [4]:
W_input_hidden = np.asarray(
    [[.9,.3,.4],
    [.2,.8,.2],
    [.1,.5,.6]])

W_hidden_output = np.asarray(
    [[.3,.7,.5],
    [.6,.5,.2],
    [.8,.1,.9]])

print("input-hidden weight matrix: ")
print(W_input_hidden.shape)
print(W_input_hidden)
print("hidden-output weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

input-hidden weight matrix: 
(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
hidden-output weight matrix: 
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


#Forward Pass.
Below shows how we get the output, from our input through hidden and output layers.

In [5]:
X_hidden = np.dot(W_input_hidden,input)
print(X_hidden.shape)
print(X_hidden)

O_hidden = sigmoid_f(X_hidden)
print(O_hidden.shape)
print(O_hidden)

X_output = np.dot(W_hidden_output,O_hidden)
print(X_output.shape)
print(X_output)

O_output = sigmoid_f(X_output)
print(O_output.shape)
print(O_output)

(3, 1)
[[1.16]
 [0.42]
 [0.62]]
(3, 1)
[[0.76133271]
 [0.60348325]
 [0.65021855]]
(3, 1)
[[0.97594736]
 [0.88858496]
 [1.25461119]]
(3, 1)
[[0.72630335]
 [0.70859807]
 [0.77809706]]


O_Output is our output we get before we start training.

# Training.
We go through training by using the for loop. For every single step, we would first go through forward pass, and get the O_output value. Then, we would go through backward pass to correct our weight, in reference to the target we have setted at the beginning. For every 100th training, we would display the error, which should be decreasing as we go through.

In [6]:
print("Training starts: ")

for epoch in range (n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 100 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")
  

Training starts: 
Epoch:  0
Error:  '0.10164482186273150754
Epoch:  100
Error:  '0.02874270152474771994
Epoch:  200
Error:  '0.00818382347184943779
Epoch:  300
Error:  '0.00238255045948206935
Epoch:  400
Error:  '0.00072638309733187622
Epoch:  500
Error:  '0.00023677841254063172
Epoch:  600
Error:  '0.00008255096463840735
Epoch:  700
Error:  '0.00003036070385132342
Training has been finished.


After we go through the training, we need to go through forward pass once more to display our result, which is our last step.

In [7]:
# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)




Output after training:  
 [[0.60127786]
 [0.79691272]
 [0.5006452 ]]


For last, we display our final value of weight matrices.

In [8]:
print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Input-hidden Weight martix: 
(3, 3)
[[ 0.81474342  0.29052705  0.32421638]
 [ 0.40407065  0.82267452  0.38139613]
 [-0.49263378  0.4341518   0.07321442]]
Hidden-output Weight matrix: 
(3, 3)
[[-0.00712505  0.43671401  0.28720227]
 [ 0.91358922  0.77108557  0.4126951 ]
 [ 0.16012332 -0.44541396  0.45119395]]


#Experimenting with different weights, inputs, and targets
Based on the codes I have written above, I changed some values and ran the code again to see how the result changes.

#Experiment 1: Different weight

I have changed the two weight matrices randomly by using numpy.random.rand(shape). The result may be different every time when I run the code.

In [10]:
input = np.asarray([[0.9, 0.1, 0.8]]).T
target = np.asarray([[0.6, 0.8, 0.5]]).T

W_input_hidden = np.random.rand(3,3)
W_hidden_output = np.random.rand(3,3)

print("Randomly generated input-hidden matrix weight matrix: ")
print(W_input_hidden)
print("Randomly generated hidden-output matrix weight matrix: ")
print(W_hidden_output)

X_hidden = np.dot(W_input_hidden,input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print("Initial output: ")
print(O_output)

print("Training starts: ")

for epoch in range (n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 100 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")

# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)

print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Randomly generated input-hidden matrix weight matrix: 
[[0.25856874 0.34034678 0.74968644]
 [0.78472518 0.63019084 0.3751744 ]
 [0.1418984  0.67593364 0.49655729]]
Randomly generated hidden-output matrix weight matrix: 
[[0.76254675 0.72639746 0.70151726]
 [0.85765498 0.92271215 0.17449829]
 [0.64248408 0.12480646 0.32400829]]
Initial output: 
[[0.8219154 ]
 [0.80267792]
 [0.68002367]]
Training starts: 
Epoch:  0
Error:  '0.08166213975512984224
Epoch:  100
Error:  '0.02175169415739490464
Epoch:  200
Error:  '0.00700935674072052789
Epoch:  300
Error:  '0.00248947515880421424
Epoch:  400
Error:  '0.00091174075722192370
Epoch:  500
Error:  '0.00033776505445539979
Epoch:  600
Error:  '0.00012619987659757582
Epoch:  700
Error:  '0.00004757664364586418
Training has been finished.
Output after training:  
 [[0.60306294]
 [0.79715243]
 [0.50078087]]
Input-hidden Weight martix: 
(3, 3)
[[-0.20929704  0.28836169  0.33380575]
 [ 0.66959218  0.61739828  0.27283396]
 [-0.32334093  0.62424038  0.083

Interestingly enough, the initial O_output value differs a lot from our original weight, or even every single time when we run the code. However, after going through 800 cycles of training, the output's value is very close to our target value, or the output value from our original weight matrices. This implies that our training system has been succesfully functioning.

#Experiment 2: Different input
I have fixed the weight matrices and target, but changed the input matrix. Again, I randomly generated the input matrix.

In [11]:
input = np.random.rand(3,1)
target = np.asarray([[0.6, 0.8, 0.5]]).T

print("Randomly generated input: ")
print(input)

W_input_hidden = np.asarray(
    [[.9,.3,.4],
    [.2,.8,.2],
    [.1,.5,.6]])

W_hidden_output = np.asarray(
    [[.3,.7,.5],
    [.6,.5,.2],
    [.8,.1,.9]])

X_hidden = np.dot(W_input_hidden,input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print("Initial output: ")
print(O_output)

print("Training starts: ")

for epoch in range (n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 100 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")

# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)

print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Randomly generated input: 
[[0.38465427]
 [0.8284854 ]
 [0.88610112]]
Initial output: 
[[0.74656296]
 [0.71816416]
 [0.78640294]]
Training starts: 
Epoch:  0
Error:  '0.11020445146796310765
Epoch:  100
Error:  '0.02717157701188997049
Epoch:  200
Error:  '0.00676868746632634365
Epoch:  300
Error:  '0.00180773046281030745
Epoch:  400
Error:  '0.00051957287522118724
Epoch:  500
Error:  '0.00016087081953215790
Epoch:  600
Error:  '0.00005305165295596080
Epoch:  700
Error:  '0.00001830992764087414
Training has been finished.
Output after training:  
 [[0.6008425 ]
 [0.79765313]
 [0.50053898]]
Input-hidden Weight martix: 
(3, 3)
[[ 0.83122133  0.15186147  0.2415594 ]
 [ 0.26339817  0.93654979  0.34604593]
 [-0.12486857  0.01566812  0.08198602]]
Hidden-output Weight matrix: 
(3, 3)
[[ 0.00475043  0.37457834  0.23371182]
 [ 0.85030618  0.77910693  0.42143363]
 [ 0.25994631 -0.49279243  0.40854103]]


Once again, The initial output's value is very different by every time we run the code, but the output after training is very close to the target value.

#Experiment 3: Different Target
This time, every other values are fixed, but the target matrix's value would be randomly generated.

In [12]:
input = np.asarray([[0.9, 0.1, 0.8]]).T
target = np.random.rand(3,1)

print("Randomly generated target: ")
print(target)

W_input_hidden = np.asarray(
    [[.9,.3,.4],
    [.2,.8,.2],
    [.1,.5,.6]])

W_hidden_output = np.asarray(
    [[.3,.7,.5],
    [.6,.5,.2],
    [.8,.1,.9]])

X_hidden = np.dot(W_input_hidden,input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print("Initial output: ")
print(O_output)

print("Training starts: ")

for epoch in range (n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 100 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")

# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)

print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Randomly generated target: 
[[0.6812411 ]
 [0.98631202]
 [0.20572492]]
Initial output: 
[[0.72630335]
 [0.70859807]
 [0.77809706]]
Training starts: 
Epoch:  0
Error:  '0.40676551080385836556
Epoch:  100
Error:  '0.10566668416048097257
Epoch:  200
Error:  '0.02780403522545799727
Epoch:  300
Error:  '0.01140903483851967749
Epoch:  400
Error:  '0.00636286920830421779
Epoch:  500
Error:  '0.00423497939985790356
Epoch:  600
Error:  '0.00311696088213403661
Epoch:  700
Error:  '0.00243255512540117716
Training has been finished.
Output after training:  
 [[0.68448449]
 [0.94205669]
 [0.20617446]]
Input-hidden Weight martix: 
(3, 3)
[[1.61164226 0.37907136 1.03257089]
 [1.43220599 0.93691178 1.29529422]
 [0.08422577 0.49824731 0.58597846]]
Hidden-output Weight matrix: 
(3, 3)
[[ 0.09233761  0.49365222  0.36799084]
 [ 1.34354564  1.21979071  0.69183512]
 [-0.4396117  -1.08213337  0.07078537]]


This time, I could find an interesting result. By the value of the random target, especially if there is a big gap between the input and the target, the error may be not corrected as much as other cases. I could find some case when the error is still around 10^-3 after 700 rounds of learning. Therefore, I tried again with 4000 cycles of learning.

In [13]:
input = np.asarray([[0.9, 0.1, 0.8]]).T
target = np.random.rand(3,1)

print("Randomly generated target: ")
print(target)

W_input_hidden = np.asarray(
    [[.9,.3,.4],
    [.2,.8,.2],
    [.1,.5,.6]])

W_hidden_output = np.asarray(
    [[.3,.7,.5],
    [.6,.5,.2],
    [.8,.1,.9]])

X_hidden = np.dot(W_input_hidden,input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print("Initial output: ")
print(O_output)

print("Training starts: ")

new_n_of_epochs = 4000
for epoch in range (new_n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 500 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")

# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)

print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Randomly generated target: 
[[0.21594298]
 [0.95333917]
 [0.77472169]]
Initial output: 
[[0.72630335]
 [0.70859807]
 [0.77809706]]
Training starts: 
Epoch:  0
Error:  '0.32037729997627778511
Epoch:  500
Error:  '0.00211456596426962866
Epoch:  1000
Error:  '0.00041544777580558817
Epoch:  1500
Error:  '0.00013568249066956038
Epoch:  2000
Error:  '0.00005288969015148259
Epoch:  2500
Error:  '0.00002262416281637387
Epoch:  3000
Error:  '0.00001021979120810672
Epoch:  3500
Error:  '0.00000477664742038318
Training has been finished.
Output after training:  
 [[0.21586571]
 [0.95183258]
 [0.77480508]]
Input-hidden Weight martix: 
(3, 3)
[[1.85131743 0.40570194 1.24561549]
 [1.07063744 0.89673749 0.97389995]
 [0.73446878 0.57049653 1.16397225]]
Hidden-output Weight matrix: 
(3, 3)
[[-0.870158   -0.13779952 -0.42395235]
 [ 1.40158789  1.11068079  0.84962621]
 [ 0.64688292 -0.02262967  0.77359401]]


More learning means more precision. After I increased the number of learning cycle by 5 times, the precision of the result has been increased dramatically.

#Experiment 4: Different Weight, Input, Target All Combined
In extra, I have combined all three experiments altogether to observer if the learning process works well in any situation. I have setted the number of learning cycles by 2000.

In [14]:
input = np.random.rand(3,1)
target = np.random.rand(3,1)

print("Randomly generated input: ")
print(input)
print("Randomly generated target: ")
print(target)

W_input_hidden = np.random.rand(3,3)
W_hidden_output = np.random.rand(3,3)

print("Randomly generated input-hidden matrix weight matrix: ")
print(W_input_hidden)
print("Randomly generated hidden-output matrix weight matrix: ")
print(W_hidden_output)

X_hidden = np.dot(W_input_hidden,input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print("Initial output: ")
print(O_output)

print("Training starts: ")

new_n_of_epochs = 2000
for epoch in range (new_n_of_epochs):

  # forward pass: we set the new O_output value
  X_hidden = np.dot(W_input_hidden, input)
  O_hidden = sigmoid_f(X_hidden)
  X_output = np.dot(W_hidden_output,O_hidden)
  O_output = sigmoid_f(X_output)

  # backward pass: we correct our weight through error
  output_error = target - O_output
  hidden_error = np.dot(W_hidden_output.T, output_error)
  W_hidden_output += .1 * np.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += .1 * np.dot(hidden_error * O_hidden * (1 - O_hidden), input.T)

  # display current error for each 100th cycle
  if epoch % 250 == 0:
    print("Epoch: ", epoch)
    total_error = np.sum(output_error ** 2)
    print("Error: ", "'{0:.20f}".format(total_error))

print("Training has been finished.")

# forward pass: we set the enew O_output value
X_hidden = np.dot(W_input_hidden, input)
O_hidden = sigmoid_f(X_hidden)
X_output = np.dot(W_hidden_output,O_hidden)
O_output = sigmoid_f(X_output)

print ("Output after training:  \n", O_output)

print("Input-hidden Weight martix: " )
print(W_input_hidden.shape)
print(W_input_hidden)
print("Hidden-output Weight matrix: ")
print(W_hidden_output.shape)
print(W_hidden_output)

Randomly generated input: 
[[0.56412686]
 [0.53232055]
 [0.70905796]]
Randomly generated target: 
[[0.18460154]
 [0.26310916]
 [0.12548221]]
Randomly generated input-hidden matrix weight matrix: 
[[0.46034506 0.07657937 0.70664769]
 [0.63725002 0.04246923 0.69604317]
 [0.32939981 0.58879895 0.41933725]]
Randomly generated hidden-output matrix weight matrix: 
[[0.804401   0.2152195  0.53559772]
 [0.33275194 0.24216947 0.91707961]
 [0.67540112 0.99687395 0.01842379]]
Initial output: 
[[0.74580467]
 [0.73744694]
 [0.76542142]]
Training starts: 
Epoch:  0
Error:  '0.94946746568151718648
Epoch:  250
Error:  '0.04488506398786715201
Epoch:  500
Error:  '0.00230684831901999815
Epoch:  750
Error:  '0.00031183544776476152
Epoch:  1000
Error:  '0.00006648503588547696
Epoch:  1250
Error:  '0.00001688849365638088
Epoch:  1500
Error:  '0.00000461911361180893
Epoch:  1750
Error:  '0.00000130529279146624
Training has been finished.
Output after training:  
 [[0.18449548]
 [0.26304728]
 [0.12608151]]
I

#Summary
Through this assignment, I have learned how neural network's learing process works, based on matrix multiplication. Preciesly, the forward pass and the backward pass were the most important part of the learning process. As the input data goes through each layers, the output became closer and closer to the target value, along with correcting the weight matrices. It was interesting how the system works regardless of the input, target, or weight value.